/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.Querys;
import java.awt.event.KeyEvent;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import medelos.Factory;
import medelos.Usuario;

/**
 *
 * @author Pedro Henrique Gomes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Factory factory = new Factory();
    EntityManager jpa = factory.retornaEntidadegerenciada();
    public static Usuario userStatic = null;

    public static String usuario;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon iconEmp = new ImageIcon("src/images/growthcode.png");
        iconEmp.setImage(iconEmp.getImage().getScaledInstance(326, 174, 1));
        logoGrowth.setIcon(iconEmp);

        ImageIcon iconUser = new ImageIcon("src/images/user.png");
        iconUser.setImage(iconUser.getImage().getScaledInstance(60, 50, 1));
        user.setIcon(iconUser);

        ImageIcon iconPassword = new ImageIcon("src/images/password.png");
        iconPassword.setImage(iconPassword.getImage().getScaledInstance(60, 50, 1));
        password.setIcon(iconPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtCancelar = new javax.swing.JButton();
        senhaInput = new javax.swing.JPasswordField();
        userInput = new javax.swing.JTextField();
        logoGrowth = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtEntrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Next.png"))); // NOI18N
        jbtEntrar.setText("Entrar");
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });
        jbtEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtEntrarKeyPressed(evt);
            }
        });
        jPanel1.add(jbtEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Login:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 95, -1, -1));

        jbtCancelar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_2_16px.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jbtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtCancelarKeyPressed(evt);
            }
        });
        jPanel1.add(jbtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        senhaInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        senhaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaInputKeyPressed(evt);
            }
        });
        jPanel1.add(senhaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 119, 240, -1));

        userInput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userInputKeyPressed(evt);
            }
        });
        jPanel1.add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 240, -1));
        jPanel1.add(logoGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 328, 187));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 50));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        Login login = new Login();
        login.setVisible(false);

    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
        Tela tela = new Tela();
        tela.logar(userInput.getText(), senhaInput.getText(), jpa);
        this.setVisible(false);

    }//GEN-LAST:event_jbtEntrarActionPerformed

    private void userInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            senhaInput.grabFocus();
        }
    }//GEN-LAST:event_userInputKeyPressed

    private void senhaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Tela tela = new Tela();
            tela.logar(userInput.getText(), senhaInput.getText(), jpa);
            this.setVisible(false);
        }
    }//GEN-LAST:event_senhaInputKeyPressed

    private void jbtEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtEntrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Tela tela = new Tela();
            tela.logar(userInput.getText(), senhaInput.getText(), jpa);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtEntrarKeyPressed

    private void jbtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCancelarKeyPressed

    public void limpaCampos() {
        userInput.setText("");
        senhaInput.setText("");
        userInput.grabFocus();
    }

    public void logar() {
        Querys loginUser = new Querys();
        userStatic = loginUser.LoginUser(userInput.getText(), senhaInput.getText(), jpa);
        if (userStatic != null) {
            JOptionPane.showMessageDialog(null, "Bem vindo: " + userStatic.getNome());
            limpaCampos();
            Principal principal = new Principal();
            principal.setVisible(true);
            this.setVisible(false);

            usuario = userStatic.getNome();
        } else {
            JOptionPane.showMessageDialog(null, "User: " + userInput.getText() + " não encontrado");
            limpaCampos();
            userStatic = null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JLabel logoGrowth;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField senhaInput;
    private javax.swing.JLabel user;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables

}
